name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # The 'build' output will be 'true' if any of the specified paths have changed.
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build:
              - 'src/**/*.ts'
              - '**/*.json'
              - '**/*.js'
              - '**/*.mjs'
              - '.github/workflows/ci.yml'

  build:
    needs: changes
    if: needs.changes.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - name: Run tests with coverage
        run: npm run coverage
      - name: Publish coverage report
        if: success()
        uses: davelosert/vitest-coverage-report-action@v2
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - run: npm run smoke:upload
      - run: npm run smoke:runs
      - run: npm run smoke:tests
      - run: npm run smoke:schema
      - run: npm run smoke

  # This job runs on every push/PR to provide a clear status check,
  # even when the main build job is skipped.
  ci-gate:
    needs:
      - changes
      - build
    if: always() && (needs.changes.outputs.build == 'false')
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes detected in source files. Skipping main build."
