name: container-build

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
  workflow_dispatch: {}

concurrency:
  group: container-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REPO: ${{ vars.IMAGE_REPO }}
  OCI_REVISION: ${{ github.sha }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 100 # Fetch enough history for multi-commit pushes
      - name: Get base commit for comparison
        id: base
        run: |
          # For workflow_run, we need to find the commit BEFORE this push started
          # Strategy: Find the first commit that was already on origin/main before this push

          HEAD_SHA="${{ github.event.workflow_run.head_sha }}"

          # Walk back from HEAD to find the last commit that was on main before this push
          # We do this by checking each parent until we find one that's an ancestor of origin/main~1
          BASE_SHA="${HEAD_SHA}"
          for i in {1..20}; do
            CANDIDATE="${HEAD_SHA}~${i}"
            if ! git rev-parse "${CANDIDATE}" >/dev/null 2>&1; then
              # Reached the beginning of history
              BASE_SHA="${HEAD_SHA}~$((i-1))"
              break
            fi
            # Check if this commit exists in the reflog of origin/main (was previously on main)
            if git merge-base --is-ancestor "${CANDIDATE}" "origin/main~1" 2>/dev/null; then
              # This commit was on main before, so the push starts at the next commit
              BASE_SHA="${CANDIDATE}"
              break
            fi
          done

          echo "base=${BASE_SHA}" >> "$GITHUB_OUTPUT"
          echo "Detected push range: ${BASE_SHA}..${HEAD_SHA}"
          echo "Changed files in this range:"
          git diff --name-only "${BASE_SHA}..${HEAD_SHA}" | head -20
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # Explicitly provide base and ref for workflow_run events
          # This ensures we check ALL commits in the push, not just the last one
          base: ${{ steps.base.outputs.base }}
          ref: ${{ github.event.workflow_run.head_sha }}
          list-files: shell
          filters: |
            build:
              - 'Containerfile'
              - 'package.json'
              - 'package-lock.json'
              - 'src/**/*'
              - 'scripts/**/*.sh'
              - '.github/workflows/container-build.yml'

  build_and_push:
    name: Build and push multi-arch image
    needs: changes
    if: needs.changes.outputs.build == 'true' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.compute_tag.outputs.tag }}
    env:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - name: Check IMAGE_REPO configured
        run: |
          if [ -z "${IMAGE_REPO}" ]; then
            echo "Repository variable IMAGE_REPO is required (e.g., quay.io/<org>/horreum-mcp)" >&2
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Compute tag
        id: compute_tag
        env:
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        run: echo "tag=${HEAD_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Install buildah/podman/qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends podman buildah qemu-user-static

      - name: Login to Quay.io (podman/buildah)
        if: env.QUAY_USERNAME != '' && env.QUAY_PASSWORD != ''
        run: |
          echo "$QUAY_PASSWORD" | podman login -u "$QUAY_USERNAME" --password-stdin quay.io
          echo "$QUAY_PASSWORD" | buildah login -u "$QUAY_USERNAME" --password-stdin quay.io

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Enable binfmt (best-effort)
        run: |
          podman run --privileged --rm tonistiigi/binfmt --install all || true

      - name: Build and push
        env:
          TAG: ${{ steps.compute_tag.outputs.tag }}
        run: |
          bash scripts/build_multiarch.sh --tag "$TAG" --push --push-main

  trivy_scan:
    name: Trivy scan (image)
    needs: build_and_push
    runs-on: ubuntu-latest
    if: needs.build_and_push.result == 'success'
    steps:
      - name: Docker login (if needed)
        if: env.QUAY_USERNAME != '' && env.QUAY_PASSWORD != ''
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_REPO }}:${{ needs.build_and_push.outputs.image_tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
