name: container-build

on:
  # Trigger on push to main ONLY when relevant files change
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'scripts/**/*.sh'
      - '.github/workflows/container-build.yml'
  # Trigger on GitHub releases
  release:
    types: [published]
  workflow_dispatch: {}

concurrency:
  group: container-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REPO: ${{ vars.IMAGE_REPO }}
  OCI_REVISION: ${{ github.sha }}

jobs:
  build_scan_and_push:
    name: Build, scan, and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - name: Check IMAGE_REPO configured
        run: |
          if [ -z "${IMAGE_REPO}" ]; then
            echo "Repository variable IMAGE_REPO is required (e.g., quay.io/<org>/horreum-mcp)" >&2
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute tags
        id: compute_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            # For releases, use the release tag (e.g., v1.2.3)
            VERSION="${{ github.event.release.tag_name }}"
            echo "tag=${VERSION}" >> "$GITHUB_OUTPUT"
            echo "additional_tag=latest" >> "$GITHUB_OUTPUT"
            echo "Building release version: ${VERSION}"
          else
            # For main branch pushes, use short SHA
            SHORT_SHA="${GITHUB_SHA:0:7}"
            echo "tag=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
            echo "additional_tag=main" >> "$GITHUB_OUTPUT"
            echo "Building main branch commit: ${SHORT_SHA}"
          fi

      - name: Install buildah/podman/qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends podman buildah qemu-user-static

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Enable binfmt (best-effort)
        run: |
          podman run --privileged --rm tonistiigi/binfmt --install all || true

      - name: Build multi-arch container image
        env:
          TAG: ${{ steps.compute_tag.outputs.tag }}
        run: |
          bash scripts/build_multiarch.sh --tag "$TAG"

      - name: Install Trivy
        run: |
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb generic main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy security scan
        env:
          TAG: ${{ steps.compute_tag.outputs.tag }}
        run: |
          bash scripts/trivy_scan.sh "localhost/horreum-mcp:${TAG}"

      - name: Login to Quay.io
        if: env.QUAY_USERNAME != '' && env.QUAY_PASSWORD != ''
        run: |
          echo "$QUAY_PASSWORD" | podman login -u "$QUAY_USERNAME" --password-stdin quay.io
          echo "$QUAY_PASSWORD" | buildah login -u "$QUAY_USERNAME" --password-stdin quay.io

      - name: Push multi-arch image to registry
        env:
          TAG: ${{ steps.compute_tag.outputs.tag }}
          ADDITIONAL_TAG: ${{ steps.compute_tag.outputs.additional_tag }}
        run: |
          # Push with primary tag (SHA or version)
          echo "Pushing ${IMAGE_REPO}:${TAG}"
          buildah manifest push --all "localhost/horreum-mcp:${TAG}" \
            "docker://${IMAGE_REPO}:${TAG}"

          # Also push with additional tag (main or latest)
          echo "Pushing ${IMAGE_REPO}:${ADDITIONAL_TAG}"
          buildah manifest push --all "localhost/horreum-mcp:${TAG}" \
            "docker://${IMAGE_REPO}:${ADDITIONAL_TAG}"
